CREATE TABLE "videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "title" varchar(50) NOT NULL,
  "url" varchar(250) NOT NULL
);

CREATE TABLE "categories" (
  "id" int PRIMARY KEY NOT NULL,
  "name" varchar(70) NOT NULL
);

CREATE TABLE "user_role" (
  "id" int PRIMARY KEY NOT NULL,
  "name" varchar(70) NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "name" varchar(50) NOT NULL,
  "email" varchar(50) NOT NULL,
  "password" varchar(20) NOT NULL,
  "age" int NOT NULL,
  "role_id" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "title" varchar(50) NOT NULL,
  "description" varchar(250) NOT NULL,
  "level" varchar(50) NOT NULL,
  "teacher" varchar(100) NOT NULL,
  "category_id" int NOT NULL
);

CREATE TABLE "user_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" int,
  "course_id" int
);

CREATE TABLE "course_videos" (
  "id" int PRIMARY KEY,
  "video_id" int NOT NULL,
  "course_id" int NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "user_role" ("id");

ALTER TABLE "user_courses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_courses" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "course_videos" ADD FOREIGN KEY ("video_id") REFERENCES "videos" ("id");

ALTER TABLE "course_videos" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

-------------------------------------------------------------------------------------------------

===cardinalidad, inserciones y consultas===

INSERT INTO user_role(id, name) VALUES(1, 'student'), (2, 'teacher'), (3, 'admint');

INSERT INTO users(name, email, password, age, role_id) VALUES('luis', 'luis@gmail.com', '123', 25, 1), ('gerardo', 'gera@gmail.com', '456', 30, 2);

INSERT INTO categories(id, name) VALUES(1, 'programacion');

INSERT INTO courses(title, description, level, teacher, category_id) VALUES('programacion de objetos', 'fundamentos de la programacion de objetos', 'basico', 'gerardo', 1);

INSERT INTO categories(id, name) VALUES(2, 'estructuras de datos');

INSERT INTO courses(title, description, level, teacher, category_id) VALUES('node js', 'fundamentos de la programacion de base de datos', 'medio', 'gerardo', 2);

INSERT INTO categories(id, name) VALUES(1, 'programacion');

INSERT INTO courses(title, description, level, teacher, category_id) VALUES('programacion de objetos', 'fundamentos de la programacion de objetos', 'basico', 'gerardo', 1);

INSERT INTO categories(id, name) VALUES(2, 'estructuras de datos');

INSERT INTO courses(title, description, level, teacher, category_id) VALUES('node js', 'fundamentos de la programacion de base de datos', 'medio', 'gerardo', 2);

INSERT INTO user_courses(user_id, course_id) VALUES(1, 2);

INSERT INTO user_courses(user_id, course_id) VALUES(2, 2);

INSERT INTO course_videos(id, course_id, video_id) VALUES(1, 2, 1), (2, 3, 2);

SELECT users.name FROM users
JOIN user_courses ON user_courses.user_id = users.id;

SELECT users.name, courses.title FROM users
JOIN user_courses ON user_courses.user_id = users.id
JOIN courses ON courses.id = user_courses.course_id;

SELECT users.name, courses.title, videos.title, categories.name, courses.teacher FROM users  
JOIN user_courses ON user_courses.user_id = users.id 
JOIN courses ON courses.id = user_courses.course_id 
JOIN course_videos ON courses.id = course_videos.course_id 
JOIN videos ON videos.id = course_videos.video_id 
JOIN categories ON categories.id = courses.category_id;

INSERT INTO users (name, email, password, age, role_id) VALUES('maria', 'maria@yahoo.com', 789, 23, 1);

SELECT users.name, courses.description, videos.title, categories.name, courses.teacher FROM users 
JOIN user_courses ON user_courses.user_id = 1 
JOIN courses ON courses.id = user_courses.course_id 
JOIN course_videos ON courses.id = course_videos.course_id 
JOIN videos ON videos.id = course_videos.video_id 
JOIN categories ON categories.id = courses.category_id WHERE users.id = 1;

INSERT INTO user_courses(user_id, course_id) VALUES(1,3);

SELECT u.name, c.description, v.title, ct.name, c.teacher FROM users u JOIN user_courses uc ON uc.user_id = 1 
JOIN courses c ON c.id = uc.course_id 
JOIN course_videos cv ON c.id = cv.course_id 
JOIN videos v ON v.id = cv.video_id 
JOIN categories ct ON ct.id = c.category_id WHERE u.id = 1;

